### ISSUE TITLE
CheapThreads.jl will be renamed Polyester.jl

### ISSUE THREAD

**Issue by chriselrod** [SkyWorld117/YisyAIFramework.jl#2]
https://github.com/JuliaRegistries/General/pull/37172
The name change should happen by Monday. Not sure if CompatHelper will catch this.

All you should have to do is replace CheapThreads with Polyester. It's simply been renamed.

**Comment by SkyWorld117** [comment]
Thank you for the information, I'll change it by then.

**Comment by SkyWorld117** [comment]
CheapThreads is now replaced in v0.4.1.
